apiVersion: apps/v1
kind: Deployment
metadata:
  name: tz-api
  namespace: tz
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: api
        image: vasiliysilver/tz-api:dev
        imagePullPolicy: IfNotPresent