apiVersion: v1
kind: Service
metadata:
  name: tz-api-nodeport
  namespace: tz
spec:
  type: NodePort
  selector:
    app: tz-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
      protocol: TCP