apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tz

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres-statefulset.yaml
  - rabbitmq-statefulset.yaml
  - api-deployment.yaml
  - consumer-deployment.yaml

commonLabels:
  project: tz
  managed-by: kustomize